import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "@/components/Preline";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";
import { Suspense } from "react";
import { FacebookPixelEvents } from "@/components/Trackings/PixelTracking";
import GoogleAnalytics from "@/components/Trackings/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <GoogleAnalytics />
      <body className={`${inter.className} bg-white`}>
        <TopBar />
        <Navbar />
        {children}
        <Footer />
        <Suspense fallback={null}>
          <FacebookPixelEvents />
        </Suspense>
      </body>
      <PrelineScript />
    </html>
  );
}
